"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import { FileText, Calendar } from "lucide-react";

export default function TermsOfServicePage() {
  const lastUpdated = "January 15, 2025";

  return (
    <div className="bg-[#FDFBF7]">
      {/* Hero Section */}
      <section className="relative bg-gradient-to-br from-[#3D5A6C] to-[#5C7A4B] text-white overflow-hidden min-h-[550px] flex items-center">
        <div className="container-custom py-16 relative z-10 w-full">
          <motion.div
            className="max-w-3xl mx-auto text-center"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
          >
            <div className="inline-flex items-center gap-2 bg-[#F2C94C] text-[#3D5A6C] px-4 py-2 rounded-full font-semibold text-sm mb-6">
              <FileText className="w-4 h-4" />
              <span>Legal</span>
            </div>

            <h1 className="text-4xl md:text-5xl font-heading font-bold text-white mb-6">
              Terms of Service
            </h1>

            <div className="flex items-center justify-center gap-2 text-white">
              <Calendar className="w-4 h-4" />
              <span>Last updated: {lastUpdated}</span>
            </div>
          </motion.div>
        </div>

        {/* Wave divider */}
        <div className="absolute bottom-0 left-0 right-0">
          <svg viewBox="0 0 1440 120" className="w-full h-auto">
            <path
              fill="#FDFBF7"
              d="M0,64L48,69.3C96,75,192,85,288,80C384,75,480,53,576,48C672,43,768,53,864,58.7C960,64,1056,64,1152,58.7C1248,53,1344,43,1392,37.3L1440,32L1440,120L1392,120C1344,120,1248,120,1152,120C1056,120,960,120,864,120C768,120,672,120,576,120C480,120,384,120,288,120C192,120,96,120,48,120L0,120Z"
            />
          </svg>
        </div>
      </section>

      {/* Content */}
      <section className="section-padding">
        <div className="container-custom">
          <motion.div
            className="max-w-3xl mx-auto"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.2 }}
          >
            <div className="bg-white rounded-2xl shadow-soft p-8 md:p-12">
              <div className="prose prose-lg max-w-none">
                {/* Introduction */}
                <p className="text-gray-600 leading-relaxed text-lg">
                  Welcome to Curious Muslim. By accessing or using our website and services,
                  you agree to be bound by these Terms of Service. Please read them carefully.
                </p>

                {/* Section 1 */}
                <h2 className="text-2xl font-heading font-bold text-[#3D5A6C] mt-10 mb-4">
                  1. Acceptance of Terms
                </h2>
                <p className="text-gray-600 leading-relaxed">
                  By accessing our website at curiousmuslim.com, you agree to these Terms
                  of Service, our Privacy Policy, and any additional terms that may apply.
                  If you do not agree to these terms, please do not use our services.
                </p>

                {/* Section 2 */}
                <h2 className="text-2xl font-heading font-bold text-[#3D5A6C] mt-10 mb-4">
                  2. Products and Services
                </h2>
                <h3 className="text-xl font-heading font-bold text-[#3D5A6C] mt-6 mb-3">
                  Physical Products
                </h3>
                <p className="text-gray-600 leading-relaxed">
                  We sell physical books and related merchandise. All products are subject
                  to availability. We reserve the right to limit quantities and refuse
                  orders at our discretion.
                </p>

                <h3 className="text-xl font-heading font-bold text-[#3D5A6C] mt-6 mb-3">
                  Ask Noor AI
                </h3>
                <p className="text-gray-600 leading-relaxed">
                  Ask Noor is an AI-powered educational tool designed for children. While
                  we strive for accuracy, responses are generated by artificial intelligence
                  and should be used for educational purposes only. We recommend parental
                  supervision and consultation with qualified scholars for detailed
                  religious questions.
                </p>

                {/* Section 3 */}
                <h2 className="text-2xl font-heading font-bold text-[#3D5A6C] mt-10 mb-4">
                  3. Orders and Payment
                </h2>
                <ul className="text-gray-600 space-y-2 list-disc pl-6">
                  <li>All prices are listed in USD unless otherwise specified</li>
                  <li>Payment is required at the time of purchase</li>
                  <li>We accept major credit cards and other payment methods as displayed at checkout</li>
                  <li>Orders are subject to acceptance and availability</li>
                  <li>We reserve the right to cancel orders in cases of pricing errors or suspected fraud</li>
                </ul>

                {/* Section 4 */}
                <h2 className="text-2xl font-heading font-bold text-[#3D5A6C] mt-10 mb-4">
                  4. Shipping and Delivery
                </h2>
                <p className="text-gray-600 leading-relaxed">
                  We ship to most countries worldwide. Shipping times and costs vary by
                  location and are calculated at checkout. We are not responsible for:
                </p>
                <ul className="text-gray-600 space-y-2 list-disc pl-6">
                  <li>Delays caused by customs or local postal services</li>
                  <li>Lost packages after delivery confirmation</li>
                  <li>Incorrect addresses provided by the customer</li>
                  <li>Import duties or taxes in your country</li>
                </ul>

                {/* Section 5 */}
                <h2 className="text-2xl font-heading font-bold text-[#3D5A6C] mt-10 mb-4">
                  5. Returns and Refunds
                </h2>
                <p className="text-gray-600 leading-relaxed">
                  We want you to be happy with your purchase. Our return policy:
                </p>
                <ul className="text-gray-600 space-y-2 list-disc pl-6">
                  <li>Returns accepted within 30 days of delivery</li>
                  <li>Items must be unused and in original condition</li>
                  <li>Customer is responsible for return shipping costs</li>
                  <li>Refunds processed within 5-7 business days of receiving the return</li>
                  <li>Digital products and personalized items are non-refundable</li>
                </ul>
                <p className="text-gray-600 leading-relaxed mt-4">
                  To initiate a return, please contact us at{" "}
                  <a href="mailto:hello@curiousmuslim.com" className="text-[#3D5A6C] font-medium hover:underline">
                    hello@curiousmuslim.com
                  </a>
                </p>

                {/* Section 6 */}
                <h2 className="text-2xl font-heading font-bold text-[#3D5A6C] mt-10 mb-4">
                  6. Intellectual Property
                </h2>
                <p className="text-gray-600 leading-relaxed">
                  All content on this website, including but not limited to text, graphics,
                  logos, illustrations, and software, is the property of Curious Muslim
                  and is protected by copyright and trademark laws.
                </p>
                <p className="text-gray-600 leading-relaxed">
                  You may not:
                </p>
                <ul className="text-gray-600 space-y-2 list-disc pl-6">
                  <li>Reproduce, distribute, or sell our content without permission</li>
                  <li>Use our trademarks without written consent</li>
                  <li>Create derivative works based on our content</li>
                  <li>Remove copyright or trademark notices from any materials</li>
                </ul>

                {/* Section 7 */}
                <h2 className="text-2xl font-heading font-bold text-[#3D5A6C] mt-10 mb-4">
                  7. User Conduct
                </h2>
                <p className="text-gray-600 leading-relaxed">
                  When using our services, you agree not to:
                </p>
                <ul className="text-gray-600 space-y-2 list-disc pl-6">
                  <li>Violate any applicable laws or regulations</li>
                  <li>Infringe on the rights of others</li>
                  <li>Attempt to gain unauthorized access to our systems</li>
                  <li>Use automated tools to access our website without permission</li>
                  <li>Submit false or misleading information</li>
                  <li>Engage in any activity that disrupts our services</li>
                </ul>

                {/* Section 8 */}
                <h2 className="text-2xl font-heading font-bold text-[#3D5A6C] mt-10 mb-4">
                  8. Disclaimer of Warranties
                </h2>
                <p className="text-gray-600 leading-relaxed">
                  Our services are provided &quot;as is&quot; without warranties of any kind, either
                  express or implied. We do not warrant that:
                </p>
                <ul className="text-gray-600 space-y-2 list-disc pl-6">
                  <li>Our services will be uninterrupted or error-free</li>
                  <li>Defects will be corrected</li>
                  <li>Our website is free of viruses or harmful components</li>
                </ul>

                {/* Section 9 */}
                <h2 className="text-2xl font-heading font-bold text-[#3D5A6C] mt-10 mb-4">
                  9. Limitation of Liability
                </h2>
                <p className="text-gray-600 leading-relaxed">
                  To the fullest extent permitted by law, Curious Muslim shall not be liable
                  for any indirect, incidental, special, consequential, or punitive damages
                  arising out of your use of our services.
                </p>
                <p className="text-gray-600 leading-relaxed">
                  Our total liability for any claim shall not exceed the amount you paid
                  for the specific product or service giving rise to the claim.
                </p>

                {/* Section 10 */}
                <h2 className="text-2xl font-heading font-bold text-[#3D5A6C] mt-10 mb-4">
                  10. Indemnification
                </h2>
                <p className="text-gray-600 leading-relaxed">
                  You agree to indemnify and hold harmless Curious Muslim and its officers,
                  directors, employees, and agents from any claims, damages, or expenses
                  arising from your use of our services or violation of these terms.
                </p>

                {/* Section 11 */}
                <h2 className="text-2xl font-heading font-bold text-[#3D5A6C] mt-10 mb-4">
                  11. Changes to Terms
                </h2>
                <p className="text-gray-600 leading-relaxed">
                  We reserve the right to modify these terms at any time. We will notify
                  users of significant changes by posting a notice on our website. Your
                  continued use of our services after changes constitutes acceptance of
                  the modified terms.
                </p>

                {/* Section 12 */}
                <h2 className="text-2xl font-heading font-bold text-[#3D5A6C] mt-10 mb-4">
                  12. Governing Law
                </h2>
                <p className="text-gray-600 leading-relaxed">
                  These terms shall be governed by and construed in accordance with the
                  laws of the United States, without regard to conflict of law principles.
                </p>

                {/* Section 13 */}
                <h2 className="text-2xl font-heading font-bold text-[#3D5A6C] mt-10 mb-4">
                  13. Contact Information
                </h2>
                <p className="text-gray-600 leading-relaxed">
                  For questions about these Terms of Service, please contact us:
                </p>
                <div className="bg-[#F5EFD4] rounded-xl p-6 mt-4">
                  <p className="text-[#3D5A6C] font-medium mb-2">Curious Muslim</p>
                  <p className="text-gray-600">
                    Email:{" "}
                    <a href="mailto:legal@curiousmuslim.com" className="text-[#3D5A6C] hover:underline">
                      legal@curiousmuslim.com
                    </a>
                  </p>
                  <p className="text-gray-600">
                    General inquiries:{" "}
                    <a href="mailto:hello@curiousmuslim.com" className="text-[#3D5A6C] hover:underline">
                      hello@curiousmuslim.com
                    </a>
                  </p>
                </div>

                {/* Acknowledgment */}
                <div className="mt-10 p-6 bg-[#3D5A6C]/5 rounded-xl border border-[#3D5A6C]/10">
                  <p className="text-gray-600 text-sm">
                    By using our website and services, you acknowledge that you have read,
                    understood, and agree to be bound by these Terms of Service and our
                    Privacy Policy.
                  </p>
                </div>
              </div>
            </div>

            {/* Related Links */}
            <div className="mt-8 flex flex-wrap gap-4 justify-center">
              <Link
                href="/privacy"
                className="text-[#3D5A6C] hover:underline font-medium"
              >
                Privacy Policy
              </Link>
              <span className="text-gray-300">|</span>
              <Link
                href="/help"
                className="text-[#3D5A6C] hover:underline font-medium"
              >
                Help Center
              </Link>
              <span className="text-gray-300">|</span>
              <Link
                href="/contact"
                className="text-[#3D5A6C] hover:underline font-medium"
              >
                Contact Us
              </Link>
            </div>
          </motion.div>
        </div>
      </section>
    </div>
  );
}
